# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bed5ef78f625e9f42990375399067984fdadbd3e21e50bea7314c4afd0d1e904005dc476d131e5de26dd6cb75f7595bae602dbbe4b4c37c1510ddd277197a7e4

test:
  secret_key_base: a2341a15539a332df025c1f85b3b038e7f1e0254f6d7eb63a034c09cbdf858118956e0a289a4c1b25bcf7e075b71baf867366460f5040cb67a737236afb1b708

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
